version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://himanshu:Mongo@cluster0.xvr7fqc.mongodb.net/FAQ_Data?retryWrites=true&w=majority
      - REDIS_URL=redis://localhost:6380
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: